---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt: 
      update_cache: yes

  - name: Install apache2 package
    apt: 
      name: apache2
      state: absent

  - name: add php support for Apache2 server
    apt:
      name: libapache2-mod-php
      state: absent

